### ISSUE TITLE
Bug ao abrir Google Chrome

### ISSUE THREAD

**Issue by joanerocha** [GTI-UFRN/gti-ponto-ui#1]
Notei que ao abrir o google chrome na janela normal não estava aparecendo o nome do bolsista/estagiário, o relógio não está contando e os ícones do menu não estão sendo apresentados como deveria. Na janela anônima o sistema funciona normalmente.

**Comment by devarthurribeiro** [comment]
Provavelmente o problema é causado por um extensão Chrome.

**Comment by joanerocha** [comment]
Acabei de descobrir o problema. Estava sendo causado pela tradução automática do crhome, que estava ativada, para a página carregar normalmente, basta desativar.

**Comment by devarthurribeiro** [comment]
@joanerocha 
```
<!DOCTYPE html>
<html lang="pt-br">
<head>
```
