### ISSUE TITLE
Espelho de Ponto

### ISSUE THREAD

**Issue by joanerocha** [GTI-UFRN/gti-ponto-ui#3]
O espelho de ponto está apagando todos os dias, seria ideal que ele continuasse visível, e pudesse ser aberto por mês.

**Comment by devarthurribeiro** [comment]
Adicionado filtro por data ao espelho de ponto https://github.com/GTI-UFRN/gti-ponto-ui/commit/395ceb98fa30f0b179d0e7b1faf1f50d33d79bf8

![image](https://user-images.githubusercontent.com/12974798/47874871-b8adf600-ddf3-11e8-960f-e3484e1755f8.png)
